[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "16"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
