backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          required: false,
        }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
              required: true,
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              fields:
                [
                  { label: Image, name: img, widget: image },
                  { label: Caption, name: caption, widget: text },
                  { label: Headline, name: headline, widget: text },
                  { label: Text, name: text, widget: text },
                  { label: URL, name: url, widget: text },
                ],
            }
      - file: "src/pages/professor/index.md"
        label: "Professor"
        name: "professor"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "testimonial-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: image }
          - {
              label: "Description",
              name: "description",
              widget: string,
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Testimonials",
              name: "testimonials",
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  {
                    label: Author,
                    name: author,
                    widget: string,
                    required: false,
                  },
                  {
                    label: Style,
                    name: style,
                    widget: select,
                    options: [basic, extended],
                    default: basic,
                  },
                ],
            }
      - file: "src/pages/researcher/index.md"
        label: "Researcher"
        name: "researcher"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: image }
          - {
              label: "Description",
              name: "description",
              widget: string,
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/consultant/index.md"
        label: "Consultant"
        name: "consultant"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: image }
          - {
              label: "Description",
              name: "description",
              widget: string,
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/spoon-carver/index.md"
        label: "Spoon-carver"
        name: "spoon-carver"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: image }
          - {
              label: "Description",
              name: "description",
              widget: string,
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/articles/index.md"
        label: "Articles Page"
        name: "articles"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "articles-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Articles,
              name: articles,
              widget: list,
              fields:
                [
                  { label: Article Title, name: title, widget: string },
                  { label: Article PDF, name: pdf, widget: file },
                ],
            }
      - file: "src/pages/media/index.md"
        label: "Media Page"
        name: "media"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "media-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Items,
              name: items,
              widget: list,
              fields:
                [
                  { label: "Item Title", name: title, widget: string },
                  { label: "Item Description", name: description , widget: text, required: false },
                  { label: "Item URL", name: url, widget: "string", hint: "Add the url for YouTube, Spotify or other media source." },
                ],
            }
